services:
  logguard:
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - /var/log:/data_to_monitor:ro
      - logguard_data:/app/chat_history
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANONYMIZED_TELEMETRY=false
      - CHROMA_TELEMETRY=false

volumes:
  logguard_data:
