version: "3.9"

services:

  soc_ai:

    build: .

    container_name: soc_ai_app

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - ./data_to_monitor:/data_to_monitor
      - ./storage:/app/storage
      - ./chroma_db_v2:/app/chroma_db_v2

    restart: unless-stopped
